bitcoindevkit/BDKSwiftExampleWallet

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
- BDKSwiftExampleWallet/View/QRCodeView.swift
- BDKSwiftExampleWallet/View/ReceiveView.swift
- BDKSwiftExampleWallet/View/WalletView.swift
> ui: qrcodeview

- BDKSwiftExampleWallet/View/ReceiveView.swift
> ui: receiveview copy address button

- BDKSwiftExampleWallet/View/SendView.swift
> Added balance to SendView

- BDKSwiftExampleWallet/View/WalletView.swift
- BDKSwiftExampleWalletTests/BDKSwiftExampleWalletWalletViewModelTests.swift
> wallet: misc

- BDKSwiftExampleWallet/View/SendView.swift
Added Amount and Address TextField with the send button.
> Updated SendView

- BDKSwiftExampleWallet/View/ReceiveView.swift
- BDKSwiftExampleWallet/View/SendView.swift
> send: base logic

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
- BDKSwiftExampleWallet/View Model/OnboardingViewModel.swift
- BDKSwiftExampleWallet/View Model/ReceiveViewModel.swift
- BDKSwiftExampleWallet/View Model/SendViewModel.swift
- BDKSwiftExampleWallet/View Model/WalletViewModel.swift
- BDKSwiftExampleWallet/View/OnboardingView.swift
- BDKSwiftExampleWallet/View/ReceiveView.swift
- BDKSwiftExampleWallet/View/SendView.swift
- BDKSwiftExampleWallet/View/TabHomeView.swift
- BDKSwiftExampleWallet/View/WalletTransactionListView.swift
- BDKSwiftExampleWallet/View/WalletView.swift
> viewmodel: folder

- BDKSwiftExampleWallet/Service/Price Service/PriceService.swift
- BDKSwiftExampleWallet/View Model/WalletViewModel.swift
- BDKSwiftExampleWallet/View/WalletView.swift
> ui: price minute

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
> localization: fr 100%

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
> localization: remove stale item

- BDKSwiftExampleWallet/View Model/OnboardingViewModel.swift
- BDKSwiftExampleWallet/View Model/ReceiveViewModel.swift
- BDKSwiftExampleWallet/View Model/SendViewModel.swift
- BDKSwiftExampleWallet/View Model/WalletViewModel.swift
- BDKSwiftExampleWallet/View/ReceiveView.swift
- BDKSwiftExampleWallet/View/SendView.swift
- BDKSwiftExampleWallet/View/WalletView.swift
> refactor: ios 17.0 migration to observable

- BDKSwiftExampleWallet/View/OnboardingView.swift
- BDKSwiftExampleWallet/View/QRCodeView.swift
- BDKSwiftExampleWallet/View/ReceiveView.swift
- BDKSwiftExampleWallet/View/SendView.swift
- BDKSwiftExampleWallet/View/TabHomeView.swift
- BDKSwiftExampleWallet/View/TransactionDetailsView.swift
- BDKSwiftExampleWallet/View/WalletTransactionListView.swift
- BDKSwiftExampleWallet/View/WalletView.swift
> refactor: ios 17.0 preview

- BDKSwiftExampleWallet/View Model/ReceiveViewModel.swift
- BDKSwiftExampleWallet/View Model/SendViewModel.swift
- BDKSwiftExampleWallet/View Model/WalletViewModel.swift
- BDKSwiftExampleWalletTests/BDKSwiftExampleWalletWalletViewModelTests.swift
> refactor: mainactor

- BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
- BDKSwiftExampleWallet/View Model/WalletViewModel.swift
- BDKSwiftExampleWallet/View/WalletView.swift
> refactor: send

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
- BDKSwiftExampleWallet/Extensions/Bundle+Extensions.swift
- BDKSwiftExampleWallet/Service/Key Service/KeyService.swift
- BDKSwiftExampleWalletTests/BDKSwiftExampleWalletBundle+Extensions.swift
> keyservice: synchronize

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View/OnboardingView.swift
- BDKSwiftExampleWallet/View/SendView.swift
- BDKSwiftExampleWallet/View/WalletView.swift
> ui: button style capsule

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View/OnboardingView.swift
- BDKSwiftExampleWallet/View/ReceiveView.swift
- BDKSwiftExampleWallet/View/TransactionDetailsView.swift
- BDKSwiftExampleWallet/View/WalletTransactionListView.swift
- BDKSwiftExampleWallet/View/WalletView.swift
> ui: font style

- BDKSwiftExampleWallet/View/WalletView.swift
> ui: call sync only once

- .github/workflows/ios.yml
> ci: macos-13sim test off temp - taking 20+min

- BDKSwiftExampleWallet/Extensions/Int+Extensions.swift
- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View Model/WalletViewModel.swift
- BDKSwiftExampleWallet/View/TransactionDetailsView.swift
- BDKSwiftExampleWallet/View/WalletTransactionListView.swift
- BDKSwiftExampleWallet/View/WalletView.swift
> ui: wallet and transactions view

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View/OnboardingView.swift
- BDKSwiftExampleWallet/View/ReceiveView.swift
- BDKSwiftExampleWallet/View/SendView.swift
- BDKSwiftExampleWallet/View/WalletView.swift
> localization: update new strings

- BDKSwiftExampleWallet/View/WalletTransactionListView.swift
- BDKSwiftExampleWallet/View/WalletView.swift
> ui: loading indicators

- .github/workflows/ios.yml
> ci: ios.yml test

- README.md
> readme: screenshot size

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
- BDKSwiftExampleWallet/Extensions/View+Extensions.swift
- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View/QRCodeView.swift
- BDKSwiftExampleWallet/View/ReceiveView.swift
> ui: fidgetqrcodeview

- README.md
> readme: add keychainaccess dependency

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View Model/OnboardingViewModel.swift
- BDKSwiftExampleWallet/View/OnboardingView.swift
> wallet: automatically restore

- BDKSwiftExampleWallet/View Model/SendViewModel.swift
- BDKSwiftExampleWallet/View/SendView.swift
- BDKSwiftExampleWallet/View/WalletView.swift
> wallet: refresh on transaction send

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
> spm: bdk-swift 0.30.0

- BDKSwiftExampleWallet/App/BDKSwiftExampleWalletApp.swift
- BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
- BDKSwiftExampleWallet/Service/Key Service/KeyService.swift
- BDKSwiftExampleWalletTests/Service/BDKSwiftExampleWalletBDKServiceTests.swift
- BDKSwiftExampleWalletTests/Service/BDKSwiftExampleWalletKeyServiceTests.swift
- BDKSwiftExampleWalletTests/View Model/BDKSwiftExampleWalletReceiveViewModelTests.swift
- README.md
> wallet: bip84 to bip86

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
- BDKSwiftExampleWallet/Extensions/String+Extensions.swift
- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
- BDKSwiftExampleWallet/View/AddressView.swift
- BDKSwiftExampleWallet/View/AmountView.swift
- BDKSwiftExampleWallet/View/BuildTransactionView.swift
- BDKSwiftExampleWallet/View/FeeView.swift
- BDKSwiftExampleWallet/View/TabHomeView.swift
> ui: sendview

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View Model/AmountViewModel.swift
- BDKSwiftExampleWallet/View/AmountView.swift
> ui: add balance confirmed

- README.md
> readme: bip-86

- .github/workflows/ios.yml
> ci: xcode 15.0.1 / iphone 15 / ios 17.0.1

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
> spm: bitcoinui 1.0.3

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
- BDKSwiftExampleWallet/Extensions/BDK+Extensions/BDKError+Extensions.swift
- BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
Updating from bdk-swift 0.30.0 to 0.31.0
https://github.com/bitcoindevkit/bdk-swift/releases/tag/0.31.0
> spm: bdk-swift 0.31.0

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
- BDKSwiftExampleWallet/App/BDKSwiftExampleWalletApp.swift
- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
- BDKSwiftExampleWallet/Service/Key Service/KeyService.swift
- BDKSwiftExampleWallet/View Model/OnboardingViewModel.swift
- BDKSwiftExampleWallet/View Model/SettingsViewModel.swift
- BDKSwiftExampleWallet/View Model/TabHomeViewModel.swift
- BDKSwiftExampleWallet/View/OnboardingView.swift
- BDKSwiftExampleWallet/View/SettingsView.swift
- BDKSwiftExampleWallet/View/TabHomeView.swift
- BDKSwiftExampleWalletTests/Service/BDKSwiftExampleWalletKeyServiceTests.swift
Adds the ability to add/import words when creating wallet.
> feat: add words

- BDKSwiftExampleWallet/Extensions/BDK+Extensions/Network+Extensions.swift
- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
- BDKSwiftExampleWallet/Service/Key Service/KeyService.swift
- BDKSwiftExampleWallet/Utilities/Constants.swift
- BDKSwiftExampleWallet/View Model/OnboardingViewModel.swift
- BDKSwiftExampleWallet/View Model/SettingsViewModel.swift
- BDKSwiftExampleWallet/View/OnboardingView.swift
- BDKSwiftExampleWallet/View/SettingsView.swift
> feat: add network

- BDKSwiftExampleWallet/View Model/AmountViewModel.swift
- BDKSwiftExampleWallet/View Model/BuildTransactionViewModel.swift
- BDKSwiftExampleWallet/View Model/FeeViewModel.swift
- BDKSwiftExampleWallet/View Model/OnboardingViewModel.swift
- BDKSwiftExampleWallet/View Model/ReceiveViewModel.swift
- BDKSwiftExampleWallet/View Model/SettingsViewModel.swift
- BDKSwiftExampleWallet/View Model/TabHomeViewModel.swift
- BDKSwiftExampleWallet/View Model/WalletViewModel.swift
- BDKSwiftExampleWallet/View/AmountView.swift
- BDKSwiftExampleWallet/View/TabHomeView.swift
> chore: main actor

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View/AmountView.swift
- BDKSwiftExampleWallet/View/BuildTransactionView.swift
- BDKSwiftExampleWallet/View/OnboardingView.swift
- BDKSwiftExampleWalletTests/View Model/BDKSwiftExampleWalletReceiveViewModelTests.swift
> ui: onboarding text layout

- .github/workflows/ios.yml
> ci: macos 14

- BDKSwiftExampleWallet/Utilities/Constants.swift
> misc: esplora constant

- BDKSwiftExampleWallet/View/AddressView.swift
- BDKSwiftExampleWallet/View/OnboardingView.swift
> ui: textfield submit label

- BDKSwiftExampleWallet/View/AddressView.swift
- BDKSwiftExampleWallet/View/AmountView.swift
- BDKSwiftExampleWallet/View/BuildTransactionView.swift
- BDKSwiftExampleWallet/View/FeeView.swift
- BDKSwiftExampleWallet/View/OnboardingView.swift
- BDKSwiftExampleWallet/View/ReceiveView.swift
- BDKSwiftExampleWallet/View/SeedView.swift
- BDKSwiftExampleWallet/View/SettingsView.swift
- BDKSwiftExampleWallet/View/TabHomeView.swift
- BDKSwiftExampleWallet/View/TransactionDetailsView.swift
- BDKSwiftExampleWallet/View/WalletTransactionListView.swift
- BDKSwiftExampleWallet/View/WalletView.swift
> ui: add accessibility large previews

- BDKSwiftExampleWallet/View/ReceiveView.swift
- BDKSwiftExampleWallet/View/TabHomeView.swift
- BDKSwiftExampleWallet/View/TransactionDetailsView.swift
- BDKSwiftExampleWallet/View/WalletTransactionListView.swift
> ui: support larger system font

- BDKSwiftExampleWallet/View Model/ReceiveViewModel.swift
> ui: textfield trim whitespace and new lines

- BDKSwiftExampleWallet/Utilities/Constants.swift
> misc: signet esplora

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
- BDKSwiftExampleWallet/Info.plist
- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View/AddressView.swift
> ui: scan address qr

- BDKSwiftExampleWallet/View/BuildTransactionView.swift
> ui: txid post-send

- BDKSwiftExampleWallet/View/BuildTransactionView.swift
> ui: transaction total

- BDKSwiftExampleWallet/View/AddressView.swift
> ui: address view buttons

- BDKSwiftExampleWallet/Service/Key Service/KeyService.swift
> misc: keyservice sync value

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View Model/AmountViewModel.swift
- BDKSwiftExampleWallet/View Model/BuildTransactionViewModel.swift
- BDKSwiftExampleWallet/View Model/FeeViewModel.swift
- BDKSwiftExampleWallet/View Model/ReceiveViewModel.swift
- BDKSwiftExampleWallet/View Model/SeedViewModel.swift
- BDKSwiftExampleWallet/View Model/SettingsViewModel.swift
- BDKSwiftExampleWallet/View Model/TabHomeViewModel.swift
- BDKSwiftExampleWallet/View Model/WalletViewModel.swift
- BDKSwiftExampleWallet/View/AddressView.swift
- BDKSwiftExampleWallet/View/AmountView.swift
- BDKSwiftExampleWallet/View/BuildTransactionView.swift
- BDKSwiftExampleWallet/View/FeeView.swift
- BDKSwiftExampleWallet/View/ReceiveView.swift
- BDKSwiftExampleWallet/View/SeedView.swift
- BDKSwiftExampleWallet/View/SettingsView.swift
- BDKSwiftExampleWallet/View/TabHomeView.swift
- BDKSwiftExampleWallet/View/WalletView.swift
> feat: error alerts

- BDKSwiftExampleWallet/View Model/BuildTransactionViewModel.swift
- BDKSwiftExampleWallet/View/WalletView.swift
> misc: remove notification state

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View Model/BuildTransactionViewModel.swift
- BDKSwiftExampleWallet/View Model/TabHomeViewModel.swift
- BDKSwiftExampleWallet/View/BuildTransactionView.swift
> ui: transaction view no checkmark on error

- BDKSwiftExampleWallet/View Model/BuildTransactionViewModel.swift
- BDKSwiftExampleWallet/View/AmountView.swift
- BDKSwiftExampleWallet/View/WalletView.swift
> ui: adding back in newTransactionSent + root

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
- BDKSwiftExampleWallet/View Model/TransactionDetailsViewModel.swift
- BDKSwiftExampleWallet/View/TransactionDetailsView.swift
- BDKSwiftExampleWallet/View/WalletTransactionListView.swift
> ui: open url

- BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
> feat: descriptor private

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View/OnboardingView.swift
> misc: team + identifier

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
> spm: bdk-swift 0.31.1

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
> misc: update fr localizable strings

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
> misc: update fr localizable strings 98%

- .github/workflows/ios.yml
- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
- BDKSwiftExampleWallet/Extensions/BDK+Extensions/Double+Extensions.swift
- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
- BDKSwiftExampleWallet/View Model/WalletViewModel.swift
- BDKSwiftExampleWallet/View/WalletView.swift
- BDKSwiftExampleWalletTests/Extensions/BDKSwiftExampleWalletDouble+Extensions.swift
- BDKSwiftExampleWalletTests/View Model/BDKSwiftExampleWalletWalletViewModelTests.swift
> feat: inspect spks for requests

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View/SettingsView.swift
Fixes a few areas of the UI:
FROM
TO
> ui: settingsview

- BDKSwiftExampleWallet/View/WalletTransactionsListItemView.swift
> ui: transaction list item date font

- BDKSwiftExampleWallet/View/WalletTransactionsListItemView.swift
> ui: color on confirmation status

- BDKSwiftExampleWallet/View/WalletTransactionListView.swift
> ui: list row background clear

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View Model/SettingsViewModel.swift
- BDKSwiftExampleWallet/View/SettingsView.swift
If need to full scan for any reason, add ability to.
> feat: settings full scan

- BDKSwiftExampleWallet/App/BDKSwiftExampleWalletApp.swift
- BDKSwiftExampleWallet/View/TabHomeView.swift
- BDKSwiftExampleWallet/View/WalletTransactionListView.swift
> chord: live previews

- BDKSwiftExampleWallet/Extensions/BDK+Extensions/BDKError+Extensions.swift
- BDKSwiftExampleWallet/Extensions/FileManager+Extensions.swift
- BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
- BDKSwiftExampleWallet/View Model/WalletViewModel.swift
> spm: local build alpha-12

- BDKSwiftExampleWallet/View/AddressView.swift
> chore: address view alerts

- BDKSwiftExampleWallet/View Model/BuildTransactionViewModel.swift
- BDKSwiftExampleWallet/View/BuildTransactionView.swift
> chore: build transaction view transaction extraction

- BDKSwiftExampleWalletTests/Service/BDKSwiftExampleWalletBDKServiceTests.swift
- BDKSwiftExampleWalletTests/View Model/BDKSwiftExampleWalletSendViewModelTests.swift
- BDKSwiftExampleWalletTests/View Model/BDKSwiftExampleWalletWalletViewModelTests.swift
> tests: update service and view model tests

- BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
- BDKSwiftExampleWallet/Service/Key Service/KeyService.swift
- README.md
> chore: services

- BDKSwiftExampleWallet/View/TransactionDetailsView.swift
- BDKSwiftExampleWallet/View/WalletTransactionListView.swift
> chore: view error alert

- README.md
> readme: update name and functionality

- BDKSwiftExampleWallet/Extensions/FileManager+Extensions.swift
- BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
> chore: use default url documents directory

- BDKSwiftExampleWallet/View/AddressView.swift
- BDKSwiftExampleWallet/View/AmountView.swift
- BDKSwiftExampleWallet/View/BuildTransactionView.swift
- BDKSwiftExampleWallet/View/FeeView.swift
- BDKSwiftExampleWallet/View/OnboardingView.swift
- BDKSwiftExampleWallet/View/ReceiveView.swift
- BDKSwiftExampleWallet/View/SeedView.swift
- BDKSwiftExampleWallet/View/SettingsView.swift
- BDKSwiftExampleWallet/View/TabHomeView.swift
- BDKSwiftExampleWallet/View/TransactionDetailsView.swift
- BDKSwiftExampleWallet/View/WalletTransactionListView.swift
- BDKSwiftExampleWallet/View/WalletTransactionsListItemView.swift
> ui: use dynamic type size instead of size category

- BDKSwiftExampleWallet/View/WalletView.swift
> ui: transaction text

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
- BDKSwiftExampleWallet/Service/Key Service/KeyService.swift
- BDKSwiftExampleWalletTests/Service/BDKSwiftExampleWalletKeyServiceTests.swift
> feat: use trait on mnemonic + descriptor

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View Model/OnboardingViewModel.swift
- BDKSwiftExampleWallet/View/OnboardingView.swift
- BDKSwiftExampleWallet/View/SeedPhraseView.swift
- BDKSwiftExampleWallet/View/SeedView.swift
> ui: twelve words view

- BDKSwiftExampleWallet/View Model/BuildTransactionViewModel.swift
Fixes Build Transaction Error.
`Build Transaction Error` psbt is nil.
> fix: build transaction error psbt

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
- BDKSwiftExampleWallet/View/AddressFormattedView.swift
- BDKSwiftExampleWallet/View/AddressView.swift
- BDKSwiftExampleWallet/View/ReceiveView.swift
Visually formatted address similar to what Design Guide proposes
> feat: visual formatted address

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View/OnboardingView.swift
- BDKSwiftExampleWallet/View/SeedView.swift
> spm: bitcoinui main

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
> spm: bitcoinui 1.0.6

- BDKSwiftExampleWallet/Extensions/BDK+Extensions/BDKError+Extensions.swift
- BDKSwiftExampleWallet/Extensions/BDK+Extensions/Transaction+Extensions.swift
- BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
- BDKSwiftExampleWallet/Service/BDK Service/BDKSwiftExampleWalletError.swift
- BDKSwiftExampleWallet/View Model/BuildTransactionViewModel.swift
- BDKSwiftExampleWallet/View Model/TransactionDetailsViewModel.swift
- BDKSwiftExampleWallet/View/BuildTransactionView.swift
- BDKSwiftExampleWallet/View/TransactionDetailsView.swift
- BDKSwiftExampleWallet/View/WalletTransactionsListItemView.swift
> spm: local bindings alpha 13

- BDKSwiftExampleWallet/View/SettingsView.swift
> ui: settingsview use navigation stack instead of navigation view

- BDKSwiftExampleWallet/View/AmountView.swift
> ui: amountview remove navigation view

- README.md
> readme: build steps for 1.0 and pre-1.0

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View/Settings/SettingsView.swift
> ui: settings view background

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View Model/Activity/ActivityListViewModel.swift
- BDKSwiftExampleWallet/View/Activity/ActivityListView.swift
- BDKSwiftExampleWallet/View/Activity/LocalOutputItemView.swift
- BDKSwiftExampleWallet/View/Activity/LocalOutputListView.swift
> misc: name output

- BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
> misc: descriptor secret

- BDKSwiftExampleWallet/View/Activity/TransactionListView.swift
> fix: transaction detail amount logic

- BDKSwiftExampleWallet/View/WalletView.swift
> ui: only if synced show all

- BDKSwiftExampleWallet/View/Activity/TransactionDetailView.swift
- BDKSwiftExampleWallet/View/Activity/TransactionListView.swift
- README.md
> misc: format

- BDKSwiftExampleWallet/View/Activity/ActivityListView.swift
> feat: activity list view animation

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View/Send/AddressView.swift
> feat: custom scanner view

- BDKSwiftExampleWallet/View/Send/AddressView.swift
- BDKSwiftExampleWallet/View/TabHomeView.swift
- BDKSwiftExampleWallet/View/WalletView.swift
> ui: receive moved from tabview to main view

- BDKSwiftExampleWallet/View/TabHomeView.swift
- BDKSwiftExampleWallet/View/WalletView.swift
> ui: send moved from tabview to main view

- BDKSwiftExampleWallet/Assets.xcassets/bitcoinsign.arrow.down.symbolset/Contents.json
- BDKSwiftExampleWallet/Assets.xcassets/bitcoinsign.arrow.down.symbolset/bitcoinsign.arrow.down.svg
- BDKSwiftExampleWallet/Assets.xcassets/bitcoinsign.arrow.up.symbolset/Contents.json
- BDKSwiftExampleWallet/Assets.xcassets/bitcoinsign.arrow.up.symbolset/bitcoinsign.arrow.up.svg
- BDKSwiftExampleWallet/View/Activity/TransactionDetailView.swift
- BDKSwiftExampleWallet/View/Receive/ReceiveView.swift
> ui: custom b symbol for receiveview + transactiondetailview

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View/Receive/ReceiveView.swift
- BDKSwiftExampleWallet/View/Settings/SettingsView.swift
- BDKSwiftExampleWallet/View/TabHomeView.swift
- BDKSwiftExampleWallet/View/WalletView.swift
> ui: move settingsview from tab view to main view

- BDKSwiftExampleWallet/View/WalletView.swift
> ui: move qrcode buttons from toolbar to bottom of view

- BDKSwiftExampleWallet/View/WalletView.swift
> ui: move show all button

- BDKSwiftExampleWallet/View/Activity/TransactionDetailView.swift
> ui: transaction detail view symbols

- BDKSwiftExampleWallet/View/Send/AddressView.swift
> ui: paste button

- BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
- BDKSwiftExampleWallet/Utilities/Constants.swift
- BDKSwiftExampleWallet/View Model/OnboardingViewModel.swift
- BDKSwiftExampleWallet/View/OnboardingView.swift
> service: default signet + ensure wallet delete

- BDKSwiftExampleWallet/View/WalletView.swift
> feat: refresh walletview from getaddress

- BDKSwiftExampleWallet/View/Send/FeeView.swift
> ui: fee view sf symbol

- BDKSwiftExampleWallet/View/Activity/ActivityListView.swift
- BDKSwiftExampleWallet/View/Activity/LocalOutputListView.swift
> fix: output to unspent

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
[bdk-swift 1.0.0-beta.2](https://github.com/bitcoindevkit/bdk-swift/releases/tag/1.0.0-beta.2)
> spm: remote bdk-swift 1.0.0-beta.2

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- README.md
> readme: remote bdk-swift 1.0

- BDKSwiftExampleWallet/View/Send/BuildTransactionView.swift
> ui: limit address characters max in buildtransactionview

- BDKSwiftExampleWallet/View/WalletView.swift
> ui: call balance first in walletview task

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
- BDKSwiftExampleWallet/Extensions/BDK+Extensions/ChainPosition+Extensions.swift
- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
- BDKSwiftExampleWallet/View Model/WalletViewModel.swift
- BDKSwiftExampleWallet/View/Activity/TransactionListView.swift
> feat: transactions sort

- BDKSwiftExampleWallet/View/OnboardingView.swift
- BDKSwiftExampleWallet/View/Send/BuildTransactionView.swift
- BDKSwiftExampleWallet/View/Settings/SeedView.swift
> ui: button text color

- BDKSwiftExampleWallet/Assets.xcassets/AccentColor.colorset/Contents.json
> ui: universal accent color

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View/WalletView.swift
> ui: price animation

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View Model/Send/BuildTransactionViewModel.swift
- BDKSwiftExampleWallet/View/OnboardingView.swift
- BDKSwiftExampleWallet/View/Send/BuildTransactionView.swift
> chore: remove regtest and disable send

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View/Settings/SeedView.swift
> ui: footnote on seedview

- BDKSwiftExampleWallet/View/WalletView.swift
> ui: balance animation

- BDKSwiftExampleWallet/View/WalletView.swift
> ui balance animation removal

- README.md
> readme: description

- BDKSwiftExampleWallet/View/Activity/TransactionDetailView.swift
> ui: transactiondetailview address clickable

- BDKSwiftExampleWallet/View/WalletView.swift
> ui: price animation match

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View/OnboardingView.swift
> chore: remove testnet

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
> spm: bdk-swift 1.0.0-beta.5

- .github/pull_request_template.md
> chore: pr template checkbox for ui

- README.md
Adds the TestFlight link to the README.
> readme: add testflight link

- BDKSwiftExampleWallet/View Model/WalletViewModel.swift
Adding a sleep purely for animation if a user has low number of scripts to be able to see the UI animation
> ui: animation delay for less scripts

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
> deps: bump bitcoinui to 1.0.8

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
- BDKSwiftExampleWallet/Extensions/BDK+Extensions/CanonicalTx+Extensions.swift
- BDKSwiftExampleWallet/Extensions/BDK+Extensions/ChainPosition+Extensions.swift
- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View/Activity/TransactionDetailView.swift
- BDKSwiftExampleWallet/View/Activity/TransactionItemView.swift
> spm: local build of beta 6

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
- BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
Uses two new functions exposed on bdk-ffi.
Using a local build of bdk-swift, so wait on this PR until bdk-ffi code is merged then pull that new tagged bdk-swift in
Only works for BIP86
> feat: isMultipath and fingerprint

- BDKSwiftExampleWallet/View/WalletView.swift
> fix: balance spacing no currency symbol

- BDKSwiftExampleWallet/View Model/OnboardingViewModel.swift
> refactor: onboarding create wallet

- BDKSwiftExampleWallet/View/WalletView.swift
> chore: remove swipe

- BDKSwiftExampleWallet/View/WalletView.swift
> ui: balance feedback

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
- BDKSwiftExampleWallet/View/Activity/TransactionListView.swift
- BDKSwiftExampleWallet/View/OnboardingView.swift
> feat: testnet4

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
- BDKSwiftExampleWallet/View Model/HomeViewModel.swift
- BDKSwiftExampleWallet/View/HomeView.swift
> fix: saved esplora and wallet load

- BDKSwiftExampleWallet/Resources/Localizable.xcstrings
- BDKSwiftExampleWallet/View/HomeView.swift
> fix: remove loading view

- BDKSwiftExampleWallet.xcodeproj/project.pbxproj
> spm: bdk-swift 1.1

- BDKSwiftExampleWallet/View/Activity/LocalOutputItemView.swift
Fix amount of Unspent list
#306
> fix: show unspent amount

- BDKSwiftExampleWallet/Extensions/BDK+Extensions/Persister+Extensions.swift
- BDKSwiftExampleWallet/Extensions/Int+Extensions.swift
- BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
- BDKSwiftExampleWalletTests/Extensions/BDKSwiftExampleWalletInt+Extensions.swift
> fix: could not load wallet

- BDKSwiftExampleWallet/View/OnboardingView.swift
> chore: onboarding text

- .github/workflows/ios.yml
> ci: xcode26 ios26 macos26
