bitcoindevkit/BDKSwiftExampleWallet

BDKSwiftExampleWallet.xcodeproj/project.pbxproj
BDKSwiftExampleWallet/Extensions/Int+Extensions.swift
BDKSwiftExampleWallet/View/WalletView.swift
BDKSwiftExampleWalletTests/BDKSwiftExampleWalletInt+Extensions.swift

Updating the denomination of a balance in the UI
Taking inspiration from [Bitcoin Design](https://bitcoin.design/guide/designing-products/units-and-symbols/)

ui: sats denomination

---

BDKSwiftExampleWallet.xcodeproj/project.pbxproj
BDKSwiftExampleWallet/Resources/Localizable.xcstrings
BDKSwiftExampleWallet/View/OnboardingView.swift

Structured the wallet for Localization.
Translated the wallet from english to french.

Added Localizable Strings for wallet translation from english to french

---

BDKSwiftExampleWallet/Extensions/FileManager+Extensions.swift
BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
BDKSwiftExampleWallet/Service/BDK Service/BDKSwiftExampleWalletError.swift

chore: add migration

---

BDKSwiftExampleWallet/Extensions/BDK+Extensions/BDKError+Extensions.swift
BDKSwiftExampleWallet/Extensions/BDK+Extensions/CanonicalTx+Extensions.swift
BDKSwiftExampleWallet/Resources/Localizable.xcstrings
BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
BDKSwiftExampleWallet/View Model/Activity/ActivityListViewModel.swift
BDKSwiftExampleWallet/View Model/OnboardingViewModel.swift
BDKSwiftExampleWallet/View Model/TabHomeViewModel.swift
BDKSwiftExampleWallet/View Model/WalletViewModel.swift
BDKSwiftExampleWallet/View/Activity/TransactionDetailView.swift
BDKSwiftExampleWallet/View/Activity/TransactionItemView.swift

`bdk-ffi`
Use local bindings of https://github.com/bitcoindevkit/bdk-ffi/pull/582
`bdk` releases
https://github.com/bitcoindevkit/bdk/releases/tag/v1.0.0-beta.1
https://github.com/bitcoindevkit/bdk/releases/tag/v1.0.0-beta.2
I did have to delete keychain since I was getting `LoadWithPersistError.CouldNotLoad`

spm: local build beta.2

---

BDKSwiftExampleWallet.xcodeproj/project.pbxproj
BDKSwiftExampleWallet/Resources/Localizable.xcstrings
BDKSwiftExampleWallet/View/HomeView.swift
BDKSwiftExampleWallet/View/Send/AddressView.swift
BDKSwiftExampleWallet/View/Send/AmountView.swift
BDKSwiftExampleWallet/View/WalletView.swift

ui: reorder addressview amountview

---

BDKSwiftExampleWallet/View/Activity/TransactionDetailView.swift
BDKSwiftExampleWallet/View/Activity/TransactionItemView.swift
BDKSwiftExampleWallet/View/Activity/TransactionListView.swift
BDKSwiftExampleWallet/View/HomeView.swift
BDKSwiftExampleWallet/View/OnboardingView.swift
BDKSwiftExampleWallet/View/Receive/ReceiveView.swift
BDKSwiftExampleWallet/View/Send/AddressView.swift
BDKSwiftExampleWallet/View/Send/AmountView.swift
BDKSwiftExampleWallet/View/Send/BuildTransactionView.swift
BDKSwiftExampleWallet/View/Send/FeeView.swift
BDKSwiftExampleWallet/View/Settings/SeedView.swift
BDKSwiftExampleWallet/View/Settings/SettingsView.swift
BDKSwiftExampleWallet/View/WalletView.swift

ui: previews

---

BDKSwiftExampleWallet/App/BDKSwiftExampleWalletApp.swift
BDKSwiftExampleWallet/View/Settings/SettingsView.swift
BDKSwiftExampleWallet/View/WalletView.swift

Needed to take an additional step after moving `SettingsView` https://github.com/bitcoindevkit/BDKSwiftExampleWallet/commit/cc04fb7715ad89021f4efd5096e5fb2c291df307#diff-14dcc2a8985f81138ad163fdb832935379eae058cfc81d02c87734c7538d03c6

fix: settingsview delete seed

---

BDKSwiftExampleWallet/Resources/Localizable.xcstrings
BDKSwiftExampleWallet/View/OnboardingView.swift
BDKSwiftExampleWallet/View/Send/FeeView.swift
BDKSwiftExampleWallet/View/Settings/SeedView.swift

ui: colors

---

BDKSwiftExampleWallet/Resources/Localizable.xcstrings
BDKSwiftExampleWallet/View/OnboardingView.swift

ui: import view

---

BDKSwiftExampleWallet/App/BDKSwiftExampleWalletApp.swift
BDKSwiftExampleWallet/View Model/HomeViewModel.swift
BDKSwiftExampleWallet/View Model/OnboardingViewModel.swift
BDKSwiftExampleWallet/View/HomeView.swift
BDKSwiftExampleWallet/View/Send/AddressView.swift
BDKSwiftExampleWallet/View/WalletView.swift

refactor: navigation, codescanner, homeview no words

---

BDKSwiftExampleWallet/Resources/Localizable.xcstrings
BDKSwiftExampleWallet/View/OnboardingView.swift
BDKSwiftExampleWallet/View/Settings/SeedView.swift

ui: collapse importview into onboardingview

---

BDKSwiftExampleWallet/Resources/Localizable.xcstrings
BDKSwiftExampleWallet/View/OnboardingView.swift
BDKSwiftExampleWallet/View/Send/BuildTransactionView.swift
BDKSwiftExampleWallet/View/Send/FeeView.swift
BDKSwiftExampleWallet/View/WalletView.swift

feat: more accessibility

---

BDKSwiftExampleWallet/Resources/Localizable.xcstrings
BDKSwiftExampleWallet/View/Send/BuildTransactionView.swift

ui: buildtransactionview layout

---

BDKSwiftExampleWallet/View/Activity/ActivityListView.swift
BDKSwiftExampleWallet/View/Activity/LocalOutputItemView.swift
BDKSwiftExampleWallet/View/Activity/TransactionDetailView.swift
BDKSwiftExampleWallet/View/Activity/TransactionItemView.swift
BDKSwiftExampleWallet/View/Receive/ReceiveView.swift
BDKSwiftExampleWallet/View/Send/AddressView.swift
BDKSwiftExampleWallet/View/Send/AmountView.swift
BDKSwiftExampleWallet/View/Send/BuildTransactionView.swift
BDKSwiftExampleWallet/View/Send/FeeView.swift
BDKSwiftExampleWallet/View/Settings/SettingsView.swift
BDKSwiftExampleWallet/View/WalletView.swift

refactor: foregroundcolor to foregroundstyle

---

BDKSwiftExampleWallet/View/Settings/SettingsView.swift

ui: settingsview listrowbackground color

---

BDKSwiftExampleWallet/Assets.xcassets/AccentColor.colorset/Contents.json
BDKSwiftExampleWallet/View/Activity/TransactionDetailView.swift
BDKSwiftExampleWallet/View/OnboardingView.swift
BDKSwiftExampleWallet/View/Receive/ReceiveView.swift
BDKSwiftExampleWallet/View/Send/AmountView.swift
BDKSwiftExampleWallet/View/Send/BuildTransactionView.swift
BDKSwiftExampleWallet/View/Send/FeeView.swift
BDKSwiftExampleWallet/View/Settings/SeedView.swift

ui: color from orange to primary

---

BDKSwiftExampleWallet/Utilities/Constants.swift

refactor: reorder testnet list

---

BDKSwiftExampleWallet/View Model/Send/BuildTransactionViewModel.swift
BDKSwiftExampleWallet/View/Send/AmountView.swift

ui: amount content transition animation

---

BDKSwiftExampleWallet/View/Receive/ReceiveView.swift

#232 can't reproduce on my end but this is a nice fix for it I think (just make receive address clickable as well as the actually copy button)

ui: receiveview address clickable

---

BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
BDKSwiftExampleWallet/View Model/Settings/SeedViewModel.swift
BDKSwiftExampleWallet/View/Settings/SeedView.swift

chore: rename some services to clients

---

BDKSwiftExampleWallet/Resources/Localizable.xcstrings
BDKSwiftExampleWallet/View Model/Activity/TransactionListViewModel.swift
BDKSwiftExampleWallet/View/Activity/TransactionListView.swift

ui: link to faucet if no transactions

---

BDKSwiftExampleWallet/Utilities/Constants.swift
BDKSwiftExampleWallet/View/Settings/SeedView.swift

ui: seedview copy button timing

---

BDKSwiftExampleWallet/Resources/Localizable.xcstrings
BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
BDKSwiftExampleWallet/View Model/Activity/TransactionDetailViewModel.swift
BDKSwiftExampleWallet/View Model/Activity/TransactionListViewModel.swift
BDKSwiftExampleWallet/View Model/OnboardingViewModel.swift
BDKSwiftExampleWallet/View Model/Settings/SettingsViewModel.swift
BDKSwiftExampleWallet/View/Activity/TransactionDetailView.swift
BDKSwiftExampleWallet/View/Activity/TransactionListView.swift
BDKSwiftExampleWallet/View/OnboardingView.swift
BDKSwiftExampleWallet/View/Settings/SettingsView.swift

chore: add testnet back

---

BDKSwiftExampleWallet/Resources/Localizable.xcstrings
BDKSwiftExampleWallet/View Model/Settings/SeedViewModel.swift
BDKSwiftExampleWallet/View/Settings/SeedView.swift

Try's to solve #230 
Still a WIP and not exactly what we want because we don't have these yet:
- ~Only copies descriptor, but not change descriptor~
- ~does not have "share" button (other related request)~
- ~descriptor format is prv~
- descriptor format uses tick not "h" `/86'/1'/0'/0/*`

ui: export descriptor

---

BDKSwiftExampleWallet.xcodeproj/project.pbxproj
BDKSwiftExampleWallet/Resources/Localizable.xcstrings
BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
BDKSwiftExampleWallet/View Model/OnboardingViewModel.swift
BDKSwiftExampleWallet/View Model/Settings/WalletRecoveryViewModel.swift
BDKSwiftExampleWallet/View Model/WalletViewModel.swift
BDKSwiftExampleWallet/View/OnboardingView.swift
BDKSwiftExampleWallet/View/Settings/SeedView.swift
BDKSwiftExampleWallet/View/Settings/SettingsView.swift
BDKSwiftExampleWallet/View/Settings/WalletRecoveryView.swift
BDKSwiftExampleWallet/View/WalletView.swift

feat: import descriptor+xpub

---

BDKSwiftExampleWallet.xcodeproj/project.pbxproj
BDKSwiftExampleWallet/BDKSwiftExampleWallet.entitlements
BDKSwiftExampleWallet/Info.plist
BDKSwiftExampleWallet/View Model/Receive/ReceiveViewModel.swift
BDKSwiftExampleWallet/View/Receive/ReceiveView.swift

feat: verify address

---

BDKSwiftExampleWallet/View/Settings/SettingsView.swift
BDKSwiftExampleWallet/View/Settings/WalletRecoveryView.swift

ui: settings views

---

BDKSwiftExampleWallet/Resources/Localizable.xcstrings
BDKSwiftExampleWallet/View/Receive/ReceiveView.swift

ui: button placement receiveview

---

BDKSwiftExampleWallet.xcodeproj/project.pbxproj
BDKSwiftExampleWallet/Extensions/BDK+Extensions/UIScreen+Extensions.swift
BDKSwiftExampleWallet/View/OnboardingView.swift
BDKSwiftExampleWallet/View/Receive/ReceiveView.swift
BDKSwiftExampleWallet/View/Send/AmountView.swift
BDKSwiftExampleWallet/View/Settings/SettingsView.swift

Makes some fixes for iPhone SE devices.
#247  #265 and other.

ui: fix for iphone se device

---

BDKSwiftExampleWallet.xcodeproj/project.pbxproj
BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift

deps: bdk-swift 1.0.0-beta.7

---

BDKSwiftExampleWallet/View/OnboardingView.swift

ui: onboarding

---

BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift

chore: stopgap

---

BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
BDKSwiftExampleWallet/View Model/HomeViewModel.swift

fix: network switch

---

BDKSwiftExampleWallet.xcodeproj/project.pbxproj
BDKSwiftExampleWallet/Extensions/BDK+Extensions/LocalOutput+Extensions.swift
BDKSwiftExampleWallet/Extensions/BDK+Extensions/Network+Extensions.swift
BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
BDKSwiftExampleWallet/Utilities/Constants.swift
BDKSwiftExampleWallet/View Model/OnboardingViewModel.swift

spm: bdk-swift 4e3783cfaee98e14ed12aee3cf1d63b2fc99705b (1.1.0-rc.1)

---

BDKSwiftExampleWallet.xcodeproj/project.pbxproj
BDKSwiftExampleWallet/Extensions/BDK+Extensions/Connection+Extensions.swift
BDKSwiftExampleWallet/Extensions/BDK+Extensions/Network+Extensions.swift
BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
BDKSwiftExampleWallet/Utilities/Constants.swift

Refactoring connection creation in BitcoinKit for cleaner code in BDKService file.
Tiny PR to simplify the code readability.

improv: simplify create wallet code

---

BDKSwiftExampleWallet.xcodeproj/project.pbxproj
BDKSwiftExampleWallet/Extensions/BDK+Extensions/Balance+Extensions.swift
BDKSwiftExampleWallet/Extensions/BDK+Extensions/SentAndReceivedValues+Extensions.swift
BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
BDKSwiftExampleWallet/View/Activity/TransactionListView.swift

spm: bdk-swift 1.2.0

---

.github/workflows/ios.yml
.gitignore
BDKSwiftExampleWallet/Extensions/BDK+Extensions/Amount+Extensions.swift
BDKSwiftExampleWallet/Extensions/BDK+Extensions/Balance+Extensions.swift
BDKSwiftExampleWallet/Extensions/BDK+Extensions/Connection+Extensions.swift
BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
BDKSwiftExampleWallet/Utilities/Constants.swift
BDKSwiftExampleWallet/View Model/Receive/ReceiveViewModel.swift
BDKSwiftExampleWallet/View Model/Settings/SettingsViewModel.swift

chore: warnings

---

BDKSwiftExampleWallet/View/WalletView.swift

The icon arrow.trianglehead.clockwise is only available on iOS 18. To maintain compatibility with the project’s iOS 17 deployment target, this PR replaces it with arrow.clockwise.

chore: fix little warning

---

BDKSwiftExampleWallet/Extensions/Int+Extensions.swift
BDKSwiftExampleWallet/Model/BalanceDisplayFormat.swift
BDKSwiftExampleWallet/View/Home/BalanceView.swift
BDKSwiftExampleWalletTests/Extensions/BDKSwiftExampleWalletInt+Extensions.swift

This PR added ₿-only format on balance screen view and resolve the [issue](https://github.com/bitcoindevkit/BDKSwiftExampleWallet/issues/298)
Reference
https://bitcoin.design/guide/designing-products/units-and-symbols/#sample-mockups

feat: added balance ₿-only format(bip177)

---

BDKSwiftExampleWallet/Resources/Localizable.xcstrings
BDKSwiftExampleWallet/View/Send/FeeView.swift

Was getting it looking like "-8" fee sometimes because of the dash, so replacing that.

ui: fee view format

---

BDKSwiftExampleWallet.xcodeproj/project.pbxproj
BDKSwiftExampleWallet/App/BDKSwiftExampleWalletApp.swift
BDKSwiftExampleWallet/Extensions/Notification+Extensions.swift
BDKSwiftExampleWallet/Resources/Localizable.xcstrings
BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
BDKSwiftExampleWallet/Service/BDK Service/BDKSwiftExampleWalletError.swift
BDKSwiftExampleWallet/Service/Key Service/KeyService.swift
BDKSwiftExampleWallet/View Model/OnboardingViewModel.swift
BDKSwiftExampleWallet/View/OnboardingView.swift
BDKSwiftExampleWalletTests/Service/BDKSwiftExampleWalletBDKServiceTests.swift

Abstracting client into its own type (in hopes of adding additional client types as PR's on top of this)

refactor: client

---

BDKSwiftExampleWallet/Extensions/BDK+Extensions/CbfClient+Extensions.swift
BDKSwiftExampleWallet/Service/BDK Service/BDKService.swift
BDKSwiftExampleWallet/View Model/WalletViewModel.swift
BDKSwiftExampleWallet/View/Home/ActivityHomeHeaderView.swift
BDKSwiftExampleWallet/View/WalletView.swift

kyoto follow ups
